config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'about' => 'pages#about'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximium: 50}
  validates :description, presence: true, length: { minimum: 3, maximium: 300}
  validates :image, presence: true
  validates :user_id, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_secure_password
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, uniqueness: {:case_sensitive => false}, length: {minimum: 5, maximum: 25}
  validates :email, :presence => true , uniqueness: true, length: {maximum: 105}, :format => {:with => VALID_EMAIL_REGEX}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i(edit update show destroy)

  def index 
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    article_hash = article_params
    if article_hash
      @article = Article.new(article_hash)
      @article.user = User.first
      save_article
    else
      flash[:notice] = 'Sorry, An error occurred! Please try again'
      flash[:color] = 'red'
      redirect_back fallback_location: @post
    end
  end

  def update
    image_id = @article.image_remote_id
    if @article.update(article_params)
      flash[:notice] = 'Article was successfully updated'
      flash[:color] = 'green'
      update_uploaded_image image_id
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def edit; end

  def show; end

  def destroy
    image_id = @article.image_remote_id
    if @article.destroy
      flash[:notice] = 'Article was successfully deleted'
      flash[:color] = 'red'
      delete_uploaded_image image_id
    else
      flash[:notice] = 'Sorry, An error occurred! Article could not be deleted'
      flash[:color] = 'red'
    end
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    parameters = params.require(:article).permit(:title, :description, :image)
    image_hash = upload_image(parameters[:image])
    if image_hash
      parameters[:image_remote_url] = image_hash['secure_url']
      parameters[:image_remote_id] = image_hash['public_id']
      return parameters
    end
    return false
  end

  def upload_image(image)
    begin
      return Cloudinary::Uploader.upload(image)
    rescue
      return false
    end
  end

  def update_uploaded_image(image_id)
    begin
      Cloudinary::Uploader.destroy(image_id, :public_id => image_id, :invalidate => true)
    rescue
      return false
    end
  end

  def delete_uploaded_image(image_id)
    begin
      Cloudinary::Uploader.destroy(image_id, :invalidate => true)
    rescue
      return false
    end
  end

  def save_article
    if @article.save
      flash[:notice] = 'Article was successfully created'
      flash[:color] = 'blue'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end

    def about
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_delete_modal.html.erb
<!-- Delete Modal Structure -->
<div id="delete-modal" class="modal">
  <div class="modal-header">
    <h5>Delete Confirmation</h5>
  </div>
  <form id="delete-form" action="", method="post", class="col-4">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="hidden" name="_method" value="delete" />
    <div class="modal-content">
      <div class="row center">
        <h5>
          <i class="material-icons left" style="color: darkred">warning</i>
          Are you sure you want to delete this article?
        </h5>
        <h6></h6>
      </div>
    </div>
    <div class="modal-footer center">
      <button id="close-button" class="modal-close btn waves-effect waves-light right" >
        Cancel
        <i class="material-icons left">clear</i>
      </button>
      <button id="delete-button" class="modal-action modal-close btn waves-effect waves-light right" type="submit" name="action">
        Yes delete it!
        <i class="material-icons left">delete</i>
      </button>
    </div>
  </form>
</div>

app/views/articles/_form.html.erb
<div class="row" style="background-color: white; padding: 20px;">
 <form id="article-form" action="<%= action %>", method="post", class="col-12">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= hidden_tag %>
  <div class="row">
    <div class="input-field col s12">
      <input id="article-title-field" type="text" class="validate" name="article[title]" minlength="3" required placeholder="TITLE" <% if article.title?  %> value="<%= article.title %>"<% end %> >
    </div>
    <div class="input-field col s12">
      <input id="article-image-field" type="url" class="validate" name="article[image]" required placeholder="IMAGE URL" <% if article.image?  %> value="<%= article.image %>"<% end %> image_remote_url="<%= article.image_remote_url %>" >
    </div>
    <div class="input-field col s12">
      <textarea id="description-textarea" class="materialize-textarea" name="article[description]" minlength="3" required placeholder="DESCRIPTION"><% if article.description? %><%= article.description %> <% end %></textarea>
    </div>
    <div class="input-field col s12">
      <button class="btn waves-effect waves-light right" type="submit" name="action"><%= submit_button %>
        <i class="material-icons right">send</i>
      </button>
      <a href="<%= articles_url %>" class="btn" style="background-color: #2196F3;">
        Back to articles listing
        <i class="material-icons right">keyboard_return</i>
      </a>
    </div>
  </div>
 </form>
</div>

app/views/articles/_form_errors.html.erb
<div>	
  <% if @article.errors.any? %>
    <h5>The following errors prevented the Article from getting created</h5>
    <% @article.errors.full_messages.each do |msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
    <% end %>
  <% end %>
</div>

	

app/views/articles/edit.html.erb
<%= render('form_errors') %>
<%=
 render partial: 'form',
        locals: {
          article: @article,
          submit_button: "Update Article",
          action: article_path(@article.id),
          hidden_tag: hidden_field_tag("_method", "patch")
        }
%>

app/views/articles/index.html.erb
<div class="row">
  <div class="col s12 ">
    <h1 class="center">Articles</h1>
  </div>
  <div id="index-page-add-article-btn" class="fixed-action-btn">
    <a href="<%= new_article_url %>" class="btn-floating btn-large waves-effect waves-light red right tooltipped pulse" data-tooltip="Add a new article">
      <i class="material-icons">add</i>
    </a>
  </div>
  <div class="col s12">
    <div class="row">
      <% @articles.each do |article| %>
        <div class="col s12 m6 l3">
          <div class="card index-article-card">
            <div class="card-image">
              <img class="materialboxed" width="100%" height="300px" src="<%= cl_image_path(article.image_remote_url) %> ">
              <div class="fixed-action-btn index-page-article-menu-btn" >
                <a class="btn-floating btn-large green">
                  <i class="large material-icons">menu</i>
                </a>
                <ul>
                  <li>
                    <a id="<%= article.id %>" href="#delete-modal" class="btn-floating red delete-article" data="<%= article.title %>">
                      <i class="material-icons">delete</i>
                    </a>
                  </li>
                  <li>
                    <a href="<%= edit_article_path(article) %>" class="btn-floating blue">
                      <i class="material-icons">mode_edit</i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="card-content">
              <a href="<%= article_path(article) %>" class="card-title center index-page-article-title"><%= article.title %></a>
              <p><%= article.description.truncate(200, separator: ' ') %></p>
            </div>
            <div class="card-action center">
              <p><%= article.user.username %>&nbsp; | &nbsp; <%= article.created_at.strftime("%B %d, %Y")%></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= render partial: 'delete_modal' %>

app/views/articles/new.html.erb
<h1 class="center">Create an Article</h1>
<%= render ('form_errors') %>
<%= render partial: 'form',
           locals: {
             article: @article,
             submit_button: "Create Article",
             action: articles_path,
             hidden_tag: nil
           }
%>

app/views/articles/show.html.erb
<div class="row">
  <div class="col s12 m12 l7 xl7">
    <div class="row">
      <div id="article-title" class="col s12">
        <p><%= @article.title %><br/><span><i class="material-icons large center" style="line-height: 0.5px; ">remove</i></span></p>
      </div>
      <div id="article-image" class="col s12" >
        <img class="materialboxed" width="100%" src="<%= cl_image_path(@article.image_remote_url, :crop => :fill) %> ">
      </div>
      <div id="article-description" class="col s12">
        <p><%= @article.description %></p>
      </div>
    </div>
    <a href="<%= articles_url %>" class="btn" style="background-color: #2196F3; margin-top: 10px;">
      Back to articles listing
      <i class="material-icons right">keyboard_return</i>
    </a>
    <a href="<%= edit_article_path %>" class="btn" style="margin-top: 10px;">
      Edit Article
      <i class="material-icons right">mode_edit</i>
    </a>
    <a id="<%= @article.id %>" style="background-color: #F44336; margin-top: 10px;" class="delete-article btn" href="#delete-modal" data="<%= @article.title %>">
      Delete Article
      <i class="material-icons right">delete</i>
    </a>

  </div>
  <%= render partial: "layouts/right_aside_section", locals: {article: @article} %>
  <%= render partial: 'delete_modal' %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer center">
  <div class="section">
    <i class="small fa fa-facebook"></i>
    <i class="small fa fa-instagram"></i>
    <i class="small fa fa-twitter"></i>
    <i class="small fa fa-google-plus"></i>
    <i class="small fa fa-youtube-play"></i>
    <p>Copyright 2017 </p>
  </div>
</footer>
    

app/views/layouts/_navigation.html.erb
<ul id="category_submenu" class="dropdown-content">
	<li><a href="#!">LIFESTYLE</a></li>
	<li class="divider"></li>
	<li><a href="#!">TRAVEL</a></li>
	<li class="divider"></li>
	<li><a href="#!">PICK</a></li>
	<li class="divider"></li>
	<li><a href="#!">FINANCE</a></li>
	<li class="divider"></li>
	<li><a href="#!">SPORT</a></li>
	<li class="divider"></li>
	<li><a href="#!">MOVIES</a></li>
</ul>
<ul id="category_submenu2" class="dropdown-content">
	<li><a href="#!">LIFESTYLE</a></li>
	<li class="divider"></li>
	<li><a href="#!">TRAVEL</a></li>
	<li class="divider"></li>
	<li><a href="#!">PICK</a></li>
	<li class="divider"></li>
	<li><a href="#!">FINANCE</a></li>
	<li class="divider"></li>
	<li><a href="#!">SPORT</a></li>
	<li class="divider"></li>
	<li><a href="#!">MOVIES</a></li>
</ul>
<nav>
	<div class="nav-wrapper">
		<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
		<ul class="left hide-on-med-and-down">
			<li><a href="<%= root_path %>">Home</a></li>
			<li><a href="<%= articles_path %>">Articles</a></li>
			<li><a href="mobile.html">Users</a></li>
			<li><a class="dropdown-button" href="#!" data-activates="category_submenu">Categories<i class="material-icons right">arrow_drop_down</i></a></li>
			<li><a href="<%= about_path %>">About</a></li>
		</ul>
		<ul class="right hide-on-med-and-down">
			<li><a href="mobile.html">Login</a></li>
			<li><a href="mobile.html">Sign Up</a></li>
		</ul>
		<ul class="side-nav" id="mobile-demo">
			<li><a href="<%= root_path %>">Home</a></li>
			<li><a href="<%= articles_path %>">Articles</a></li>
			<li><a href="mobile.html">Users</a></li>
			<li><a class="dropdown-button" href="#!" data-activates="category_submenu2">Categories<i class="material-icons right">arrow_drop_down</i></a></li>
			<li><a href="<%= about_path %>">About</a></li>
			<li><a href="mobile.html">Login</a></li>
			<li><a href="mobile.html">Sign Up</a></li>
		</ul>
	</div>
</nav>

app/views/layouts/_right_aside_section.html.erb
<div class="col s12 m12 l4 xl4 right">
  <h1>Show Selected Article</h1>
  <p>Title: <%= article.title %></p>
  <p>Description: <%= article.description %></p>
  <a href="<%= edit_article_path %>">Edit Article</a> | <a href="<%= articles_url %>">Back to articles listing</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>AlphaBlog</title>
 <%= csrf_meta_tags %>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div id="content" >
  <header>
    <div class="navbar-fixed">
      <%= render('layouts/navigation') %>
    </div>
  </header>
  <main id="main">
    <div id="main-content">
      <%= yield %>
    </div>
  </main>
  <footer>
    <%= render('layouts/footer') %>
  </footer>
</div>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script>
    var message = "<%= flash[:notice] %>";
    var color = "<%= flash[:color] %>";
    Materialize.toast(message, 1000, color);
  </script>
</body>
</html>

app/views/pages/about.html.erb
<h1>404 PAGE NOT FOUND</h1>
<a href="<%= root_path %>">Home</a>

app/views/pages/home.html.erb
<div class="section" style="border-bottom: solid 0.1px lightgrey; height: 20%">
	<div class="row center">
		<h3>ALPHA BLOG</h3>
		<p style="color: gray">JUST ANOTHER RAILS SITE</p>
	</div>
</div>
<div class="section">
	<div class="row">
		<h5>Section 2</h5>
		<p>Stuff</p>
	</div>
</div>
<div class="section">
	<div class="row">
		<h5>Section 3</h5>
		<p>Stuff</p>
	</div>
</div>